### ISSUE TITLE
Eslint question

### ISSUE THREAD

**Issue by Piero87** [KleoPetroff/react-webpack-boilerplate#145]
Hi,
First of all this is a **GREAT** boilerplate, really amazing, I hope you continue to update and support it, and I hope more people star it. I have only one question, why you doesn't use eslint in this way:

```
...
module: {
  preLoaders: [
    {
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'eslint-loader'
    },
  ],
  loaders: [
    {
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'react-hot-loader!babel-loader'
    }
  ]
},
...
```

In this way the eslint is called every time and not only when you call the `lint` script in `package.json`. So you have continue feedback from eslint.
This is not a criticism, but only a question as I have just started studying these frameworks and I want to deep in them.

**Comment by KleoPetroff** [comment]
That is actually a pretty nice idea, @Piero87. I've played a bit with the loader and it seems to be working great with webpack 3.

Something I've been thinking is should I keep the eslint rules as it is, using Airbnb's config, or rework them to return warnings instead of errors (similar to create-react-app). What do you thing?

Regardless of that, I would most certainly integrate eslint-loader to the project. I will test is a a bit more first on a branch, [react-webpack-boilerplate/eslint-loader](https://github.com/KleoPetroff/react-webpack-boilerplate/tree/eslint-loader), and I hope to add it to the project by the next couple of days.

Once again, thanks for the great suggestion! :tada:

**Comment by Piero87** [comment]
I appreciate you think is a good idea, I think that to write a good JavaScript You have to stick to the guides, otherwise you risk only with the warnings of not looking and writing maybe in a bad way. If you work in a team for example is really important that everyone write the same code As if everyone was the same person, giving continuity to the code. So the Eslint give you a block with error that you must to fix before go on. I take that suggestion reading this amazing blog:
https://www.robinwieruch.de/react-eslint-webpack-babel/#eslintBabel
https://www.robinwieruch.de/minimal-react-webpack-babel-setup/#babelSetup

**Comment by KleoPetroff** [comment]
From what I understand you favor eslint's errors more than the warnings, right?

**Comment by Piero87** [comment]
Yes, I'm always in favor of writing a good javascript, so I in this way is better the error than the warning. I don't know if it's possible in webpack, but you could use a parameter to enable or disable it at the startup of the script, maybe with two start different start script.

**Comment by KleoPetroff** [comment]
Sounds fair. I will leave it as it is then.

**Comment by KleoPetroff** [comment]
With #148, the project now supports continuous linting.
