### ISSUE TITLE
Blank Screen after rendering in production

### ISSUE THREAD

**Issue by katakeynii** [KleoPetroff/react-webpack-boilerplate#378]
After rendering app it shows a blank screen. The bundle file is loaded but not executed.

**Comment by KleoPetroff** [comment]
What errors are you getting?

**Comment by mam10eks** [comment]
I had the same problem.

It was caused since I served the produced files not by a webserver (since I simply wanted a html-report-file).

Subsequently the Router was misconfigured for me.

Hence I changed the router configuration in `app/config/Root.js` from `<Route path="/" component={App} exact />` to `<Route path="/*" component={App} exact />`.
